version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # - npm install -g vite@latest
      # - npm install -g create-react-app
  pre_build:
    commands:
      # - npm 
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  base-directory: dist/
  files:
    - '**/*'